# Generated by Django 3.2.16 on 2022-11-22 19:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0003_alter_salonservice_users'),
        ('multilanding', '0003_alter_multilandingdomain_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultilandingLocale',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('lang', models.CharField(max_length=2, verbose_name='Lang')),
                ('alias', models.CharField(max_length=100, verbose_name='Alias')),
                ('text', models.CharField(max_length=100, verbose_name='Text')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locales', to='service.category')),
                ('multilanding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locales', to='multilanding.multilanding')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locales', to='service.salonservice')),
            ],
            options={
                'verbose_name': 'Multilanding Locale',
                'verbose_name_plural': 'Multilanding Locales',
                'db_table': 'multilanding.locales',
            },
        ),
        migrations.AddIndex(
            model_name='multilandinglocale',
            index=models.Index(fields=['lang', 'alias'], name='multilandin_lang_b16fc5_idx'),
        ),
        migrations.AddConstraint(
            model_name='multilandinglocale',
            constraint=models.UniqueConstraint(fields=('lang', 'alias'), name='unque_lang'),
        ),
    ]
