# Generated by Django 3.2.16 on 2022-11-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0002_remove_multilandinglocale_unque_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multilandinglocale',
            old_name='service',
            new_name='salon_service',
        ),
    ]
