# Generated by Django 3.2.16 on 2022-12-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0003_rename_service_multilandinglocale_salon_service'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='multilandinglocale',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('category__isnull', True), ('multilanding__isnull', True), ('salon_service__isnull', False)), models.Q(('category__isnull', False), ('multilanding__isnull', True), ('salon_service__isnull', True)), models.Q(('category__isnull', True), ('multilanding__isnull', False), ('salon_service__isnull', True)), _connector='OR'), name='check_valid_locale_entity'),
        ),
    ]
