# Generated by Django 3.2.16 on 2022-12-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0004_multilandinglocale_check_valid_locale_entity'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='multilandinglocale',
            constraint=models.UniqueConstraint(fields=('multilanding', 'lang', 'alias'), name='unque_multilanding_lang'),
        ),
        migrations.AddConstraint(
            model_name='multilandinglocale',
            constraint=models.UniqueConstraint(fields=('salon_service', 'lang', 'alias'), name='unque_salon_service_lang'),
        ),
        migrations.AddConstraint(
            model_name='multilandinglocale',
            constraint=models.UniqueConstraint(fields=('category', 'lang', 'alias'), name='unque_category_lang'),
        ),
    ]
