# Generated by Django 4.0.6 on 2022-10-26 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_created_at_user_update_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.CreateModel(
            name='AsyncCodeOperation',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('failed', 'Failed'), ('succeed', 'Succeed'), ('waiting', 'Waiting')], max_length=20)),
                ('type', models.CharField(choices=[('registration', 'Registration'), ('password_recovery', 'Password recovery')], max_length=30)),
                ('expire_date', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='async_opertaions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
