# Generated by Django 3.2.16 on 2022-11-08 11:00

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20221108_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='position',
            new_name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='thumb_image',
            field=models.CharField(blank=True, max_length=300, verbose_name='Photo Ref 80x80'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True),
        ),
    ]
