# Generated by Django 3.2.16 on 2022-11-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20221108_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Owner'), (2, 'Admin'), (3, 'Employee')], max_length=20, verbose_name='User role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'Working'), (2, 'Not working'), (3, 'Removed')], max_length=30, verbose_name='Position'),
        ),
    ]
