# Generated by Django 3.2.16 on 2022-11-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20221121_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Owner'), (2, 'Admin'), (3, 'Employee')], verbose_name='User role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'Working'), (2, 'Not working'), (3, 'Removed')], verbose_name='Position'),
        ),
    ]
