# Generated by Django 3.2.16 on 2022-11-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20221122_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asynccodeoperation',
            name='code',
            field=models.IntegerField(),
        ),
    ]
