# Generated by Django 3.2.16 on 2022-12-06 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multilanding', '0009_multilanding_sub_domain'),
        ('users', '0013_auto_20221130_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='multilanding.multilanding'),
            preserve_default=False,
        ),
    ]
