# Generated by Django 3.2.16 on 2022-12-06 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multilanding', '0011_remove_multilanding_is_active'),
        ('users', '0014_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='multilanding.multilanding'),
        ),
    ]
