# Generated by Django 3.2.16 on 2022-12-18 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='name',
        ),
    ]
