version: '3.7'

services:
  postgres:
    container_name: randevu-pg
    image: postgres:13.3
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
     - 5432:5432
    volumes:
      - dev-db-data:/var/lib/postgresql/data

  redis:
    container_name: randevu-redis
    image: redis:6-alpine
    ports:
      - 6379:6379

volumes:
  dev-db-data:
