version: "3.7"

x-app-service: &admin-service
    env_file: .env
    image: randevu-dev
    environment:
        - MEDIA_URL=/media/
        - MEDIA_ROOT=/tmp/media/
        - STATIC_URL=/static/
        - STATIC_ROOT=/tmp/static/
    networks:
        - randevu-prod-net

services:
    admin:
        <<: *admin-service
        ports:
            - "45070:8000"
        deploy:
            mode: replicated
            replicas: 1

    pg:
        image: postgres:13.3
        env_file: .env
        environment:
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_DB=$POSTGRES_DB
        ports:
            - "45045:5432"
        networks:
            - randevu-prod-net

    redis:
        container_name: randevu-redis
        image: redis:6-alpine
        ports:
            - 6379:6379

networks:
    randevu-prod-net:
        driver: bridge
