# Generated by Django 3.2.16 on 2022-11-08 10:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSchedule',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('week_day', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Sunday'), (6, 'Saturday')], max_length=30, verbose_name='Week day')),
                ('start_work_time_step', models.IntegerField(null=True, verbose_name='Start work time step')),
                ('end_work_time_step', models.IntegerField(verbose_name='End work time step')),
                ('is_day_off', models.BooleanField(default=False, verbose_name='Is day OFF')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='week_schedule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff schedule',
                'verbose_name_plural': 'Staffs schedule',
                'db_table': 'staff.schedule',
            },
        ),
        migrations.CreateModel(
            name='StaffBreak',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('start_break_time_step', models.IntegerField(verbose_name='Start break time step')),
                ('steps_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Steps amount')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='schedule.staffschedule')),
            ],
            options={
                'db_table': 'staff.break',
            },
        ),
    ]
