# Generated by Django 3.2.16 on 2022-11-10 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffbreak',
            options={'verbose_name': 'Staff break', 'verbose_name_plural': 'Staff breaks'},
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_schedule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='staffbreak',
            constraint=models.UniqueConstraint(fields=('start_break_time_step', 'schedule'), name='Single break time step'),
        ),
        migrations.AddConstraint(
            model_name='staffschedule',
            constraint=models.UniqueConstraint(fields=('week_day', 'user'), name='single schedule for one week day'),
        ),
    ]
