# Generated by Django 3.2.16 on 2022-11-10 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0003_alter_staffschedule_end_work_time_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedule', to=settings.AUTH_USER_MODEL),
        ),
    ]
