# Generated by Django 3.2.16 on 2022-11-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_staffschedule_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffschedule',
            name='is_day_off',
            field=models.BooleanField(default=True, verbose_name='Is day OFF'),
        ),
    ]
