# Generated by Django 3.2.16 on 2022-11-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_staffschedule_is_day_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffschedule',
            name='week_day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Sunday'), (6, 'Saturday')], max_length=30, verbose_name='Week day'),
        ),
    ]
