# Generated by Django 3.2.16 on 2022-11-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20221111_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffschedule',
            name='week_day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (6, 'Sunday'), (5, 'Saturday')], verbose_name='Week day'),
        ),
    ]
