# Generated by Django 3.2.16 on 2022-11-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default='hehehe', max_length=200, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='whatsapp',
            field=models.BooleanField(default=False, verbose_name='WhatsApp'),
            preserve_default=False,
        ),
    ]
