# Generated by Django 3.2.16 on 2022-12-08 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multilanding', '0015_auto_20221208_1629'),
        ('client', '0002_auto_20221129_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='multilanding.multilanding'),
        ),
    ]
