# Generated by Django 3.2.16 on 2022-12-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Email'),
        ),
    ]
