# Generated by Django 3.2.16 on 2022-12-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20221208_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='whatsapp',
            field=models.BooleanField(default=False, verbose_name='WhatsApp'),
        ),
    ]
