# Generated by Django 3.2.16 on 2023-01-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_client_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Email'),
        ),
    ]
