# Generated by Django 4.0.6 on 2022-10-26 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultilandingDomain',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(db_index=True, max_length=100, verbose_name='Domain')),
            ],
            options={
                'db_table': 'multilanding-domains',
            },
        ),
        migrations.CreateModel(
            name='Multilanding',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('sub_domian', models.CharField(db_index=True, max_length=50, verbose_name='Sub domain')),
                ('is_active', models.BooleanField(default=True)),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_domains', to='multilanding.multilandingdomain')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multilanding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'multilandings',
            },
        ),
    ]
