# Generated by Django 3.2.7 on 2022-10-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilanding', '0002_rename_sub_domian_multilanding_sub_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multilandingdomain',
            name='domain',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Domain'),
        ),
    ]
