# Generated by Django 3.2.16 on 2022-11-28 20:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('multilanding', '0003_alter_multilandingdomain_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultilandingGallery',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True, verbose_name='WhatsApp')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='multilanding',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Building'),
        ),
        migrations.AddField(
            model_name='multilanding',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='multilanding',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='multilanding',
            name='cover_img',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='multilanding',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='multilanding',
            name='googleMapApiKey',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Map API key'),
        ),
        migrations.AddField(
            model_name='multilanding',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='multilanding',
            name='langs',
            field=models.JSONField(null=True, verbose_name='Langs'),
        ),
        migrations.AddField(
            model_name='multilanding',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='multilanding',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='WhatsApp'),
        ),
    ]
