# Generated by Django 3.2.16 on 2022-11-28 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multilanding', '0004_auto_20221128_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multilanding',
            name='langs',
        ),
    ]
