# Generated by Django 3.2.16 on 2022-11-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multilanding', '0005_remove_multilanding_langs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multilanding',
            old_name='cover_img',
            new_name='cover',
        ),
    ]
