# Generated by Django 3.2.16 on 2022-12-05 12:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilanding', '0007_auto_20221205_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multilanding',
            name='sub_domain',
        ),
        migrations.AlterField(
            model_name='multilanding',
            name='gallery',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=6),
        ),
    ]
