# Generated by Django 3.2.16 on 2022-12-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multilanding', '0009_multilanding_sub_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multilanding',
            name='owner',
        ),
    ]
