# Generated by Django 3.2.16 on 2022-12-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multilanding', '0010_remove_multilanding_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multilanding',
            name='is_active',
        ),
    ]
