# Generated by Django 3.2.16 on 2022-12-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilanding', '0011_remove_multilanding_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='multilanding',
            name='dns_zone_id',
            field=models.CharField(default=123, max_length=150, verbose_name='DNS zone ID'),
            preserve_default=False,
        ),
    ]
