# Generated by Django 3.2.16 on 2022-12-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilanding', '0012_multilanding_dns_zone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='multilanding',
            name='end_work_week_day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multilanding',
            name='start_work_week_day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
