# Generated by Django 3.2.16 on 2022-12-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilanding', '0013_auto_20221208_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multilanding',
            name='end_work_week_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='multilanding',
            name='start_work_week_day',
            field=models.IntegerField(null=True),
        ),
    ]
