# Generated by Django 3.2.16 on 2022-12-19 03:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('multilanding', '0016_auto_20221214_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='multilanding',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
