# Generated by Django 3.2.16 on 2022-12-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilanding', '0017_multilanding_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='multilanding',
            name='logo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='multilanding',
            name='cover',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cover'),
        ),
    ]
