# Generated by Django 3.2.7 on 2022-11-02 09:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('backend', models.CharField(choices=[('', 'Unset'), ('anymail.backends.postmark.EmailBackend', 'Postmark')], default='', max_length=256)),
                ('from_email', models.CharField(help_text='E.g. Fedor Borshev &lt;fedor@borshev.com&gt;. MUST configure postmark!', max_length=256, verbose_name='Email sender')),
                ('backend_options', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Email configuration',
                'verbose_name_plural': 'Email configurations',
            },
        ),
        migrations.CreateModel(
            name='EmailLogEntry',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=255)),
                ('template_id', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('email', 'template_id')},
                'index_together': {('email', 'template_id')},
            },
        ),
    ]
