# Generated by Django 3.2.16 on 2022-11-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfiguration',
            name='from_email',
            field=models.CharField(help_text='E.g.Info Randevu &lt;info@randevu.beauty&gt;. MUST configure postmark!', max_length=256, verbose_name='Email sender'),
        ),
    ]
