# Generated by Django 3.2.16 on 2022-11-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_salonservice_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
    ]
