# Generated by Django 3.2.16 on 2022-11-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_remove_salonservice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonservice',
            name='image',
            field=models.CharField(default='asd', max_length=500, verbose_name='Iamge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salonservice',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='salonservice',
            name='gender',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female')], max_length=30, verbose_name='Gender'),
        ),
    ]
