# Generated by Django 3.2.16 on 2022-11-29 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20221129_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salonservice',
            old_name='users',
            new_name='employees',
        ),
    ]
