# Generated by Django 3.2.16 on 2022-11-29 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_rename_users_salonservice_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonservice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='service.category'),
        ),
    ]
