# Generated by Django 3.2.16 on 2022-11-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_salonservice_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonservice',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], verbose_name='Gender'),
        ),
    ]
