# Generated by Django 3.2.16 on 2022-12-06 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multilanding', '0011_remove_multilanding_is_active'),
        ('service', '0009_alter_salonservice_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='multilanding.multilanding'),
        ),
        migrations.AddField(
            model_name='salonservice',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='multilanding.multilanding'),
        ),
    ]
