# Generated by Django 3.2.16 on 2022-11-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_employee',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_employe_ac2327_idx',
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['employee', 'day', 'time_step'], name='appointment_employe_ae1f17_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('employee', 'day', 'time_step'), name='unique_employee'),
        ),
    ]
