# Generated by Django 3.2.16 on 2022-11-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20221115_2012'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_employee',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_employe_ae1f17_idx',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='day',
            new_name='date',
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['employee', 'date'], name='appointment_employe_cb56b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('employee', 'date', 'time_step'), name='unique_employee'),
        ),
    ]
