# Generated by Django 3.2.16 on 2022-11-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20221116_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Wait'), (2, 'In Progress'), (3, 'Done'), (5, 'Canceled')], default=0, verbose_name='Status'),
        ),
    ]
