# Generated by Django 3.2.16 on 2022-12-09 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multilanding', '0015_auto_20221208_1629'),
        ('appointment', '0005_auto_20221209_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='multilanding.multilanding'),
        ),
    ]
